# Вспомогательный код

Чтобы результаты экспериментов воспроизводились, зафиксируем seed's:

In [1]:
import torch
import random
import numpy as np


def set_random_seed(seed):
    torch.manual_seed(seed)
    torch.cuda.manual_seed(seed)
    np.random.seed(seed)
    random.seed(seed)
    torch.backends.cudnn.deterministic = True


set_random_seed(42)

Для выполнения задания рекомендуется использовать среду с аппаратным ускорителем GPU:

In [4]:
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using {device} device")

Using cuda device

Установим Transformers и необходимые библиотеки:

In [3]:
from IPython.display import clear_output

!pip install -q -U transformers accelerate git+https://github.com/huggingface/peft.git
!pip install -q datasets evaluate

clear_output()

In [4]:
!pip install -q trl
!pip install -q bitsandbytes einops #wndb
!pip install -q peft

# Задание 1. Генерация текста

Возьмите произведение Гете "Фауст" и обучите на нем модель генерации текста.

При обучении игнорируйте знаки препинания и номера страниц.

Используйте предобученную модель `sberbank-ai/rugpt3small_based_on_gpt2` из библиотеки Hugging Face. Попробуйте разные параметры модели (например, разные режимы генерации). Как меняется результат?

Импорт необходимых библиотек:

In [5]:
import torch
from transformers import Trainer, TrainingArguments
from transformers import GPT2Tokenizer, GPT2LMHeadModel
from transformers import DataCollatorForLanguageModeling
from torch.utils.data import Dataset
from IPython.display import clear_output

## Загрузка и подготовка данных

In [15]:
!wget -q https://edunet.kea.su/repo/EduNet-web_dependencies/datasets/Faust.txt

In [16]:
with open("Faust.txt") as text_file:
    faust_text = "".join(text_file.readlines())

In [17]:
faust_text

'вы вновь со мной, туманные виденья,\nмне в юности мелькнувшие давно…\nвас удержу ль во власти вдохновенья?\nбылым ли снам явиться вновь дано?\nиз сумрака, из тьмы полузабвенья\nвосстали вы… о, будь, что суждено!\nкак в юности, ваш вид мне грудь волнует,\nи дух мой снова чары ваши чует.\nвы принесли с собой воспоминанье\nвеселых дней и милых теней рой;\nвоскресло вновь забытое сказанье\nлюбви и дружбы первой предо мной;\nвсе вспомнилось: и прежнее страданье,\nи жизни бег запутанной чредой,\nи образы друзей, из жизни юной\nисторгнутых, обманутых фортуной.\nкому я пел когда-то, вдохновенный,\nтем песнь моя – увы! – уж не слышна…\nкружок друзей рассеян по вселенной,\nих отклик смолк, прошли те времена.\nя чужд толпе со скорбью, мне священной,\nмне самая хвала ее страшна,\nа те, кому моя звучала лира,\nкто жив еще, – рассеяны средь мира.\nи вот воскресло давнее стремленье\nтуда, в мир духов, строгий и немой,\nи робкое родится песнопенье,\nстеня, дрожа эоловой струной;\nв суровом сердце трепет и смиренье,\nв очах слеза сменяется слезой;\nвсе, чем владею, вдаль куда-то скрылось;\nвсе, что прошло, – восстало, оживилось!..\nдиректор, поэт и комик.\nдрузья, вы оба мне не раз\nпомочь умели в горькой доле;\nкак ваше мненье: хорошо ли\nпойдут дела теперь у нас?\nхотел бы публике я угодить на славу:\nона сама живет и жить другим дает.\nподмостки есть; театр готов; забаву\nуж предвкушает радостно народ.\nу нас ведь все к чудесному стремятся:\nглядят во все глаза и жаждут удивляться.\nмне угождать толпе хоть и не новый труд,\nно все ж меня берет невольное сомненье:\nпрекрасного они, конечно, не поймут,\nзато начитаны они до пресыщенья.\nвот дать бы пьесу нам поярче, поновей,\nпосодержательней – для публики моей!\nа ведь приятен вид толпы необозримой,\nкогда она вокруг театра наводнит\nвсю площадь и бежит волной неудержимой,\nи в двери тесные и рвется и спешит.\nнет четырех часов, до вечера далеко,\nа уж толпа кишит, пустого места нет, –\nточь-в-точь голодные пред лавкой хлебопека,\nи шею все сломить готовы за билет.\nтакие чудеса во власти лишь поэта!\nмой друг, теперь прошу: скорей ты сделай это.\nне говори мне о толпе безумной –\nона в нас мысли лучшие гнетет;\nизбавь меня от этой давки шумной,\nвлекущей мощно в свой водоворот;\nнет, тишины ищу я, многодумный, –\nлишь там поэту радость расцветет;\nтам, только там божественною властью\nлюбовь и дружба нас приводят к счастью.\nчто в глубине сердечной грудь лелеет,\nчто просится на робкие уста –\nудачно ль, нет ли, – выйти чуть посмеет\nна свет – его погубит суета!\nнет, лучше пусть годами дума зреет,\nчтоб совершенной стала красота!\nмишурный блеск родится на мгновенье,\nпрекрасному – потомства поклоненье!\nпотомство! вот о чем мне речи надоели!\nчто, если б для него – потомства – в самом деле\nи я бы перестал смешить честной народ?\nкто ж публику тогда, скажите, развлечет\nвеселой шуткою, ей нужной, без сомненья?..\nнет, как хотите, а держусь я мненья,\nчто весельчак заслужит свой почет\nи что забавник – не лишен значенья.\nкто интересен публике, мой друг,\nтот говорить с толпою может смело;\nувлечь ее – ему пустое дело,\nуспех тем легче, чем обширней круг!\nитак, смелей вперед! вы можете заставить\nфантазию, любовь, рассудок, чувство, страсть\nна сцену выступить; но не забудьте часть\nи шаловливого дурачества прибавить.\nа главное, мой друг, введите приключенья!\nглазеть на них – толпе нет выше наслажденья;\nну и пускай толпа, разиня рот, глядит…\nпричудливую ткань раскиньте перед нею –\nи вы упрочили за пьесою своею\nуспех, и к вам толпа уже благоволит.\nпусть масса массу привлекает!\nпусть каждый кое-что на вкус получит свой!\nкто много предложил, тот многим угождает –\nи вот толпа идет, довольная, домой.\nсмелее все в куски мельчайшие крошите –\nи этот винегрет успех доставит вам.\nлегко вам выдумать, легко представить нам!\nчто пользы, если вы им «целое» дадите?\nведь публика ж его расщиплет по кускам.\nи вы не видите, как гнусно и постыдно\nтакое ремесло? иль не художник я?\nдрянных писак пустая пачкотня\nу вас вошла уж в правило, как видно.\nне может нас упрек подобный оскорбить:\nведь всякий человек, рассудок свой имея,\nберет оружие, какое бьет вернее.\nс волками жить – по-волчьи выть!\nкто ваша публика, позвольте вас спросить?\nодин приходит к нам, чтоб скуку утолить.\nдругой, набив живот потуже,\nидет сюда переварить обед,\nа третий – что для нас всего, пожалуй, хуже –\nприходит нас судить по толкам из газет.\nдля них одно – театр, балы и маскарады:\nлишь любопытством весь народ гоним;\nа дамы – те идут показывать наряды:\nчтоб роль играть, не нужно платы им.\nо чем вы грезите? спуститесь-ка пониже!\nвам хорошо смотреть с надзвездной вышины!\nнет, вы взгляните-ка поближе!\nте грубы, эти холодны!\nодин от нас в приют камелий,\nдругой в игорный дом идет…\nсмешно, когда поэт зовет\nвеликих муз к ничтожной цели!\nпрошу вас об одном: побольше сочинить.\nкак можно более – вот в чем мое стремленье!\nзапутайте толпу, введите в заблужденье,\nиначе – верьте мне – ей трудно угодить.\nчто с вами? или вас коснулось вдохновенье?\nиди других ищи себе рабов:\nмне высшие права природа уделила.\nпредам ли на позор высокий дар богов?\nпродажна ли певца святая сила?\nчем трогает сердца восторженный поэт?\nкакая сила в нем стихиями владеет?\nне та ль гармония, что в сердце он лелеет,\nкоторою, творя, объемлет он весь свет?\nкогда природа-мать движеньем равнодушным\nнить вечную влечет веретеном послушным,\nкогда все сущее, сменяясь каждый час,\nв нестройный, резкий хор сливается вкруг нас, –\nкто звуки мерные в порядке размещает,\nчьей речи верный ритм живителен и тверд?\nкто единичное искусно обобщает,\nобъединяя все в торжественный аккорд?\nкто бурю выразит в борьбе страстей кипучей,\nв теченье строгих дум – зари вечерней свет?\nвесны роскошный лучший цвет\nк ногам возлюбленной бросает кто, могучий?\nкто цену придает незначащим листам,\nв прославленный венок вплетая листья эти?\nкто стережет олимп, кто друг и связь богам?\nмощь человечества, живущая в поэте!\nи долг ваш – эту мощь на деле применить!\nитак, ловите же минуты вдохновенья,\nкак ловит ловелас предлог для похожденья!\nугодно ль, например, любовь изобразить?\nслучайно сходятся – взаимное сближенье,\nзатем – свидания, надежды, опасенья;\nто счастье близко к ним, то вновь уходит вдаль,\nто ревность, то боязнь, то радость, то печаль, –\nглядишь – готов роман. и так-то все на свете.\nсмелей лишь черпайте из жизни всех людей –\nи для задуманной комедии своей\nне будете нуждаться вы в предмете.\nвсяк испытал, конечно, чувства эти,\nно редкий знает, сколько в них чудес!\nгде ни копните – тут и интерес!\nкартина попестрей, поменьше освещенья\nда искра истины средь мрака заблужденья,\nи смотришь – славное сварили вы питье,\nпо вкусу каждому: в нем всяк найдет свое.\nцвет юности идет сюда, мечтая,\nчто откровенье в пьесе он найдет,\nи нежных душ чувствительная стая\nмеланхоличной пищи сердцу ждет;\nв одном одну мечту, в другом другую будит\nрассказ искусный ваш, и каждый зритель будет,\nручаюсь, вашей пьесой восхищен:\nчто в сердце у него, то в пьесе видит он!\nони еще не прочь и плакать, и смеяться,\nвозвышенное чтить и блеском восхищаться.\nкто пожил, на того не угодишь ничем,\nа тот, кто не созрел, доволен будет всем!\nотдай же годы мне златые,\nкогда и сам я был незрел,\nкогда я песни молодые,\nне уставая, вечно пел!\nв тумане мир передо мною\nскрывался; жадною рукою\nповсюду я цветы срывал\nи в каждой почке чуда ждал.\nя беден был – и все, что надо\nдля счастья чистого, имел:\nстремленьем к истине кипел,\nи бред мечты мне был отрада!..\nотдай мне прежний жар в крови,\nмои порывы и стремленья,\nблаженство скорби, мощь любви,\nи мощной ненависти рвенье,\nчто юность! юность вам нужнее,\nкогда идете вы на бой,\nкогда красавица порой\nсама на вашей виснет шее,\nкогда конца своим трудам\nхотите быстро вы добиться,\nкогда всю ночь придется вам\nплясать, и петь, и веселиться.\nно чтоб искусною рукой\nиграть, восторги возбуждая,\nи, ловко там и сям блуждая,\nстремиться к цели подставной,\nза это старшие пускай берутся смело:\nтем больше будет вам почета, старики!\nчто старость в детство нас приводит – пустяки:\nдо самой старости мы – дети; вот в чем дело!\nдовольно слов, довольно споров,\nи комплиментов, и укоров!\nзачем болтать по пустякам?\nпора за дело взяться нам.\nк чему такие затрудненья?\nчто вдохновенья долго ждать?\nпоэт – властитель вдохновенья:\nон должен им повелевать.\nчто нужно нам – мы с вами знаем;\nнапиток крепкий мы считаем\nза лучший – дайте ж нам его!\nне забывайте ничего:\nчто можно сделать неотложно,\nзачем на завтра оставлять?\nдолжны вы сразу уловлять\nвсе то, что нужно и возможно,\nи уж из рук не выпускать!\nдля нашей сцены все пригодно;\nна ней – вы полный господин;\nберите сколько вам угодно\nи декораций, и машин,\nогней бенгальских, освещенья,\nзверей и прочего творенья,\nутесов, скал, огня, воды:\nни в чем не будет вам нужды.\nвесь мир на сцену поместите,\nлюдей и тварей пышный ряд –\nи через землю с неба в ад\nвы мерной поступью пройдите!\nгосподь, архангелы, потом мефистофель.\nзвуча в гармонии вселенной\nи в хоре сфер гремя, как гром,\nзлатое солнце неизменно\nтечет предписанным путем.\nнепостижимость мирозданья\nдает нам веру и оплот,\nи, словно в первый день созданья,\nвеличествен вселенной ход!\nи с непонятной быстротою,\nкружась, несется шар земной;\nпроходят быстрой чередою\nсиянье дня и мрак ночной;\nбушует море на просторе,\nу твердых скал шумит прибой,\nно в беге сфер земля и море\nпроходят вечно предо мной.\nгрозя земле, волнуя воды,\nбушуют бури и шумят,\nи грозной цепью сил природы\nвесь мир таинственно объят.\nсверкает пламень истребленья,\nгрохочет гром по небесам,\nно вечным светом примиренья\nтворец небес сияет нам.\nи крепнет сила упованья\nпри виде творческой руки:\nтворец, как в первый день созданья,\nтвои творенья велики!\nопять, о господи, явился ты меж нас\nза справкой о земле – что делается с нею!\nты с благосклонностью встречал меня не раз –\nи вот являюсь я меж челядью твоею.\nпрости, не мастер я по части громких слов;\nно, если б пышный слог я в ход пустить решился,\nсам рассмеялся б ты – ручаться я готов, –\nкогда б от смеха ты давно не отучился.\nмне нечего сказать о солнцах и мирах:\nя вижу лишь одни мученья человека.\nсмешной божок земли, всегда, во всех веках\nчудак такой же он, как был в начале века!\nему немножко лучше бы жилось,\nкогда б ему владеть не довелось\nтем отблеском божественного света,\nчто разумом зовет он: свойство это\nон на одно лишь мог употребить –\nчтоб из скотов скотиной быть!\nпозвольте мне – хоть этикет здесь строгий –\nсравненьем речь украсить: он на вид\nни дать ни взять – кузнечик долгоногий,\nкоторый по траве то скачет, то взлетит\nи вечно песенку старинную твердит.\nи пусть еще в траве сидел бы он уютно.\nтак нет же, прямо в грязь он лезет поминутно.\nты кончил? с жалобой одною\nявляешься ты вечно предо мною!\nиль на земле добра совсем уж нет?\nнет, что ни говори, а плох наш белый свет!\nбедняга человек! он жалок так в страданье,\nчто мучить бедняка и я не в состоянье.\nно не такой, как все; он служит по-иному;\nни пить, ни есть не хочет по-земному;\nкак сумасшедший, он рассудком слаб,\nчто чувствует и сам среди сомнений;\nвсегда в свои мечтанья погружен,\nто с неба лучших звезд желает он,\nто на земле – всех высших наслаждений,\nи в нем ничто – ни близкое, ни даль –\nне может утолить грызущую печаль.\nпока еще умом во мраке он блуждает,\nно истины лучом он будет озарен;\nсажая деревцо, садовник уже знает,\nкакой цветок и плод с него получит он.\nбьюсь об заклад: он будет мой!\nпрошу я только позволенья, –\nпойдет немедля он за мной.\nпока живет он на груди земной,\nтебе на то не будет запрещенья:\nблуждает человек, пока в нем есть стремленья.\nблагодарю: не надо мертвых мне!\nот трупов я держуся в стороне.\nнет, дайте мне здорового вполне:\nтаких я мертвецам всегда предпочитаю –\nкак кошка с мышью, с ними я играю.\nтебе позволено: иди\nи завладей его душою\nи, если можешь, поведи\nпутем превратным за собою –\nи посрамлен да будет сатана!\nзнай: чистая душа в своем стремленье смутном\nсознаньем истины полна!\nсознаньем слабым и минутным!\nигра мне эта не страшна,\nне проиграю я заклада;\nно только знайте: если мне\nподдастся он, пусть будет мой вполне:\nтриумф победы – вот моя награда!\nпусть вьется он в пыли, как тетушка моя,\nдостопочтенная змея!\nтогда явись ко мне без колебанья!\nк таким, как ты, вражды не ведал я…\nхитрец, среди всех духов отрицанья\nты меньше всех был в тягость для меня.\nслаб человек; покорствуя уделу,\nон рад искать покоя – потому\nдам беспокойного я спутника ему:\nкак бес, дразня его, пусть возбуждает к делу!\nа вы, сыны небес и рая, –\nпусть вечно радует вас красота святая,\nи ко всему, что есть и будет вновь,\nпусть проникает вас священная любовь.\nи все, что временно, изменчиво, туманно,\nобнимет ваша мысль, спокойно-постоянна.\nнебо закрывается. архангелы расходятся.\nохотно старика я вижу иногда,\nхоть и держу язык; приятно убедиться,\nчто даже важные такие господа\nумеют вежливо и с чертом обходиться!\nстаринная комната с высокими готическими сводами.\nя философию постиг,\nя стал юристом, стал врачом…\nувы! с усердьем и трудом\nи в богословье я проник –\nи не умней я стал в конце концов,\nчем прежде был… глупец я из глупцов!\nмагистр и доктор я – и вот\nтому пошел десятый год;\nя за нос провожу всегда.\nи вижу все ж, что не дано нам знанья.\nизныла грудь от жгучего страданья!\nпусть я разумней всех глупцов –\nписак, попов, магистров, докторов, –\nпусть не страдаю от пустых сомнений,\nпусть не боюсь чертей и привидений,\nпусть в самый ад спуститься я готов, –\nзато я радостей не знаю,\nнапрасно истины ищу,\nзато, когда людей учу,\nих научить, исправить – не мечтаю!\nпритом я нищ: не ведаю, бедняк,\nни почестей людских, ни разных благ…\nтак пес не стал бы жить! погибли годы!\nвот почему я магии решил\nпредаться: жду от духа слов и сил,\nчтоб мне открылись таинства природы,\nчтоб не болтать, трудясь по пустякам,\nо том, чего не ведаю я сам,\nчтоб я постиг все действия, все тайны,\nвсю мира внутреннюю связь;\nиз уст моих чтоб истина лилась –\nне слов пустых набор случайный!\nо месяц! если б в этот час\nты озарил в последний раз\nменя средь комнаты моей,\nгде я познал тоску ночей!..\nо, если б мог бродить я там\nв твоем сиянье по горам,\nмеж духов реять над вершиной,\nв тумане плавать над долиной,\nнауки праздный чад забыть,\nсебя росой твоей омыть!..\nеще ль в тюрьме останусь я?\nнора проклятая моя!\nздесь солнца луч в цветном окне\nедва-едва заметен мне;\nна полках книги по стенам\nдо сводов комнаты моей –\nони лежат и здесь и там,\nдобыча пыли и червей;\nреторт и банок целый ряд\nв пыли с приборами стоят\nна ветхих полках много лет.\nи вот твой мир! и вот твой свет!\nеще ль не ясно, почему\nизныла грудь твоя тоской,\nи больно сердцу твоему,\nи жизни ты не рад такой?\nживой природы пышный цвет,\nтворцом на радость данный нам,\nты променял на тлен и хлам,\nна символ смерти – на скелет!..\nо, прочь! беги, беги скорей\nтуда, на волю! нострадам\nчудесной книгою своей\nтебя на путь наставит сам.\nк словам природы будь не глух –\nи ты узнаешь ход светил,\nи дух твой будет полон сил,\nкогда ответит духу дух!\nчудесных знаков дивный вид\nсухой наш ум не объяснит.\nо духи! здесь вы в тишине\nвитаете: ответьте мне!\nчто за блаженство вновь в груди моей\nзажглось при этом виде, сердцу милом!\nкак будто счастье жизни юных дней\nвновь заструилось пламенно по жилам!\nначертан этот знак не бога ли рукой?\nон душу бурную смиряет,\nон сердце бедное весельем озаряет,\nон таинства природы раскрывает\nпред изумленною душой!\nне бог ли я? светло и благодатно\nвсе вкруг меня! здесь с дивной глубиной\nвсе творчество природы предо мной!\nтеперь мне слово мудреца понятно:\n«в мир духов нам доступен путь,\nно ум твой спит, изнемогая:\nо ученик! восстань, купая\nв лучах зари земную грудь!»\nкак в целом части все, послушною толпою\nсливаясь здесь, творят, живут одна другою!\nкак силы вышние в сосудах золотых\nразносят всюду жизнь божественной рукою\nи чудным взмахом крыл лазоревых своих\nвитают над землей и в высоте небесной –\nи стройно все звучит в гармонии чудесной!\nо, чудный вид! но только вид – увы!\nмне не обнять природы необъятной!\nи где же вы, сосцы природы, – вы,\nдарующие жизнь струею благодатной,\nкоторыми живет и небо и земля,\nк которым рвется так больная грудь моя?\nвы всех питаете, – что ж тщетно жажду я?\nвот знак другой. он чувства мне иные\nвнушает. дух земли, ты ближе мне, родней!\nтеперь себя я чувствую сильней –\nснесу и горе я и радости земные.\nкак будто бы вином живительным согрет,\nотважно ринусь я в обширный божий свет;\nмне хочется борьбы, готов я с бурей биться –\nи в час крушенья мне ли устрашиться?\nповсюду мрак и тишина,\nмеж туч скрывается луна,\nи лампа тихо угасает.\nнад головою в вышине\nкровавый луч во мгле сверкает,\nи в кровь, стесняя сердце мне,\nхолодный ужас проникает.\nо дух, ты здесь, ты близок – о, приди!\nкак сердце бьется у меня в груди!\nвсем существом, души всей мощным зовом\nя порываюсь к чувствам новым!\nявись, явись мне – я всем сердцем твой!\nпусть я умру – явись передо мной!\nя вызван мощным голосом твоим;\nк моей ты сфере льнул, ее ты порожденье –\nувы, твой вид невыносим!\nне ты ли сам желал с тоской упорной\nувидеть лик, услышать голос мой?\nсклонился я на зов отважный твой –\nи вот я здесь! но что за страх позорный,\nсверхчеловек, тобою овладел?\nгде мощный зов души, где тот титан могучий,\nкто мир весь обнимал, кто мыслию кипучей\nсравняться с нами, духами, хотел?\nты фауст ли, кто звать меня посмел\nвсей силою души неосторожной?\nи что ж? моим дыханьем обожжен,\nдрожит, в пыли дорожной корчась, он,\nкак червь презренный и ничтожный!\nво прах перед тобой я не склонюсь челом,\nзнай: равен я тебе, дух пламенный, во всем!\nв буре деяний, в волнах бытия\nсмерть и рожденье –\nтак на станке проходящих веков\nтку я живую одежду богов.\nты целый мир обширный обнимаешь:\nо деятельный дух, как близок я тебе!\nты близок лишь тому, кого ты постигаешь, –\nстучатся. знаю я: помощник это мой!\nпогибло все! о смерть, о муки!\nда, он пришел смутить видений чудный рой,\nничтожный червь сухой науки!\nфауст с неудовольствием отворачивается.\nпростите! что-то вслух читали вы сейчас:\nиз греческой трагедии, конечно?\nвот в этом преуспеть желал бы я сердечно:\nведь декламация в большой цене у нас!\nслучалось слышать мне, что может в деле этом\nактер священнику помочь своим советом.\nда, коль священник ваш актер и сам,\nкак мы нередко видим здесь и там.\nчто ж делать? мы живем всегда в уединенье;\nедва по праздникам покинешь свой музей,\nи то, как в телескоп, свет видишь в отдаленье.\nтак где ж найти слова, чтоб нам учить людей?\nкогда в вас чувства нет, все это труд бесцельный;\nнет, из души должна стремиться речь,\nчтоб прелестью правдивой, неподдельной\nсердца людские тронуть и увлечь!\nа вы? сидите да кропайте,\nс чужих пиров объедки подбирайте –\nи будет пестрый винегрет\nподдельным пламенем согрет.\nкогда таков ваш вкус – пожалуй, этим\nвы угодите дуракам и детям;\nно сердце к сердцу речь не привлечет,\nколь не из сердца ваша речь течет.\nнет, в красноречье – истинный успех!\nно в этом, признаюсь, я поотстал от всех.\nищи заслуги честной и бесспорной!\nк чему тебе колпак шута позорный?\nкогда есть ум и толк в словах у нас,\nречь хороша и без прикрас.\nи если то, что говорится, дельно, –\nиграть словами разве не бесцельно?\nда, ваши речи, с праздным блеском их,\nв обман лишь вводят вычурой бесплодной.\nне так ли ветер осени холодной\nшумит меж листьев мертвых и сухих?\nах, боже мой, наука так пространна,\nа наша жизнь так коротка!\nмое стремленье к знанью неустанно,\nи все-таки порой грызет меня тоска.\nкак много надо сил душевных, чтоб добраться\nдо средств лишь, чтоб одни источники найти;\nа тут – того гляди – еще на полпути\nпридется бедняку и с жизнию расстаться.\nв пергаменте ль найдем источник мы живой?\nему ли утолить высокие стремленья?\nо нет, в душе своей одной\nнайдем мы ключ успокоенья!\nпростите:

In [18]:
len(faust_text.split(" "))

51923

Удалим знаки управляющих символов и приведем текст к нижнему регистру:

In [19]:
text = (
    faust_text.replace("\n", " ")
    .replace("\r", "")
    .replace("\ufeff", "")
    .replace("\x0c", "")
)
text = "".join([char for char in text if char.isalpha() or char == " "])
text = text.lower()

In [11]:
text

'вы вновь со мной туманные виденья мне в юности мелькнувшие давно вас удержу ль во власти вдохновенья былым ли снам явиться вновь дано из сумрака из тьмы полузабвенья восстали вы о будь что суждено как в юности ваш вид мне грудь волнует и дух мой снова чары ваши чует вы принесли с собой воспоминанье веселых дней и милых теней рой воскресло вновь забытое сказанье любви и дружбы первой предо мной все вспомнилось и прежнее страданье и жизни бег запутанной чредой и образы друзей из жизни юной исторгнутых обманутых фортуной кому я пел когдато вдохновенный тем песнь моя  увы  уж не слышна кружок друзей рассеян по вселенной их отклик смолк прошли те времена я чужд толпе со скорбью мне священной мне самая хвала ее страшна а те кому моя звучала лира кто жив еще  рассеяны средь мира и вот воскресло давнее стремленье туда в мир духов строгий и немой и робкое родится песнопенье стеня дрожа эоловой струной в суровом сердце трепет и смиренье в очах слеза сменяется слезой все чем владею вдаль кудато скрылось все что прошло  восстало оживилось директор поэт и комик друзья вы оба мне не раз помочь умели в горькой доле как ваше мненье хорошо ли пойдут дела теперь у нас хотел бы публике я угодить на славу она сама живет и жить другим дает подмостки есть театр готов забаву уж предвкушает радостно народ у нас ведь все к чудесному стремятся глядят во все глаза и жаждут удивляться мне угождать толпе хоть и не новый труд но все ж меня берет невольное сомненье прекрасного они конечно не поймут зато начитаны они до пресыщенья вот дать бы пьесу нам поярче поновей посодержательней  для публики моей а ведь приятен вид толпы необозримой когда она вокруг театра наводнит всю площадь и бежит волной неудержимой и в двери тесные и рвется и спешит нет четырех часов до вечера далеко а уж толпа кишит пустого места нет  точьвточь голодные пред лавкой хлебопека и шею все сломить готовы за билет такие чудеса во власти лишь поэта мой друг теперь прошу скорей ты сделай это не говори мне о толпе безумной  она в нас мысли лучшие гнетет избавь меня от этой давки шумной влекущей мощно в свой водоворот нет тишины ищу я многодумный  лишь там поэту радость расцветет там только там божественною властью любовь и дружба нас приводят к счастью что в глубине сердечной грудь лелеет что просится на робкие уста  удачно ль нет ли  выйти чуть посмеет на свет  его погубит суета нет лучше пусть годами дума зреет чтоб совершенной стала красота мишурный блеск родится на мгновенье прекрасному  потомства поклоненье потомство вот о чем мне речи надоели что если б для него  потомства  в самом деле и я бы перестал смешить честной народ кто ж публику тогда скажите развлечет веселой шуткою ей нужной без сомненья нет как хотите а держусь я мненья что весельчак заслужит свой почет и что забавник  не лишен значенья кто интересен публике мой друг тот говорить с толпою может смело увлечь ее  ему пустое дело успех тем легче чем обширней круг итак смелей вперед вы можете заставить фантазию любовь рассудок чувство страсть на сцену выступить но не забудьте часть и шаловливого дурачества прибавить а главное мой друг введите приключенья глазеть на них  толпе нет выше наслажденья ну и пускай толпа разиня рот глядит причудливую ткань раскиньте перед нею  и вы упрочили за пьесою своею успех и к вам толпа уже благоволит пусть масса массу привлекает пусть каждый коечто на вкус получит свой кто много предложил тот многим угождает  и вот толпа идет довольная домой смелее все в куски мельчайшие крошите  и этот винегрет успех доставит вам легко вам выдумать легко представить нам что пользы если вы им целое дадите ведь публика ж его расщиплет по кускам и вы не видите как гнусно и постыдно такое ремесло иль не художник я дрянных писак пустая пачкотня у вас вошла уж в правило как видно не может нас упрек подобный оскорбить ведь всякий человек рассудок свой имея берет оружие какое бьет вернее с волками жить  поволчьи выть кто ваша публика позвольте вас спросить один приходит к нам чтоб скуку утолить другой набив живот потуже идет сюда переварить обед а третий  что для нас всего пожалуй хуже  приходит нас судить по толкам из газет для них одно  театр балы и маскарады лишь любопытством весь народ гоним а дамы  те идут показывать наряды чтоб роль играть не нужно платы им о чем вы грезите спуститеська пониже вам хорошо смотреть с надзвездной вышины нет вы взглянитека поближе те грубы эти холодны один от нас в приют камелий другой в игорный дом идет смешно когда поэт зовет великих муз к ничтожной цели прошу вас об одном побольше сочинить как можно более  вот в чем мое стремленье запутайте толпу введите в заблужденье иначе  верьте мне  ей трудно угодить что с вами или вас коснулось вдохновенье иди других ищи себе рабов мне высшие права природа уделила предам ли на позор высокий дар богов продажна ли певца святая сила чем трогает сердца восторженный поэт какая сила в нем стихиями владеет не та ль гармония что в сердце он лелеет которою творя объемлет он весь свет когда природамать движеньем равнодушным нить вечную влечет веретеном послушным когда все сущее сменяясь каждый час в нестройный резкий хор сливается вкруг нас  кто звуки мерные в порядке размещает чьей речи верный ритм живителен и тверд кто единичное искусно обобщает объединяя все в торжественный аккорд кто бурю выразит в борьбе страстей кипучей в теченье строгих дум  зари вечерней свет весны роскошный лучший цвет к ногам возлюбленной бросает кто могучий кто цену придает незначащим листам в прославленный венок вплетая листья эти кто стережет олимп кто друг и связь богам мощь человечества живущая в поэте и долг ваш  эту мощь на деле применить итак ловите же минуты вдохновенья как ловит ловелас предлог для похожденья угодно ль например любовь изобразить случайно сходятся  взаимное сближенье затем  свидания надежды опасенья то счастье близко к ним то вновь уходит вдаль то ревность то боязнь то радость то печаль  глядишь  готов роман и такто все на свете смелей лишь черпайте из жизни всех людей  и для задуманной комедии своей не будете нуждаться вы в предмете всяк испытал конечно чувства эти но редкий знает сколько в них чудес где ни копните  тут и интерес картина попестрей поменьше освещенья да искра истины средь мрака заблужденья и смотришь  славное сварили вы питье по вкусу каждому в нем всяк найдет свое цвет юности идет сюда мечтая что откровенье в пьесе он найдет и нежных душ чувствительная стая меланхоличной пищи сердцу ждет в одном одну мечту в другом другую будит рассказ искусный ваш и каждый зритель будет ручаюсь вашей пьесой восхищен что в сердце у него то в пьесе видит он они еще не прочь и плакать и смеяться возвышенное чтить и блеском восхищаться кто пожил на того не угодишь ничем а тот кто не созрел доволен будет всем отдай же годы мне златые когда и сам я был незрел когда я песни молодые не уставая вечно пел в тумане мир передо мною скрывался жадною рукою повсюду я цветы срывал и в каждой почке чуда ждал я беден был  и все что надо для счастья чистого имел стремленьем к истине кипел и бред мечты мне был отрада отдай мне прежний жар в крови мои порывы и стремленья блаженство скорби мощь любви и мощной ненависти рвенье что юность юность вам нужнее когда идете вы на бой когда красавица порой сама на вашей виснет шее когда конца своим трудам хотите быстро вы добиться когда всю ночь придется вам плясать и петь и веселиться но чтоб искусною рукой играть восторги возбуждая и ловко там и сям блуждая стремиться к цели подставной за это старшие пускай берутся смело тем больше будет вам почета старики что старость в детство нас приводит  пустяки до самой старости мы  дети вот в чем дело довольно слов довольно споров и комплиментов и укоров зачем болтать по пустякам пора за дело взяться нам к чему такие затрудненья что вдохновенья долго ждать поэт  властитель вдохновенья он должен им повелевать что нужно нам  мы с вами знаем напиток крепкий мы считаем за лучший  дайте ж нам его не забывайте ничего что можно сделать неотложно зачем на завтра оставлять должны вы сразу уловлять все то что нужно и возможно и уж из рук не выпускать для нашей сцены все пригодно на ней  вы полный господин берите сколько вам угодно и декораций и машин огней бенгальских освещенья зверей и прочего творенья утесов скал огня воды ни в чем не будет вам нужды весь мир на сцену поместите людей и тварей пышный ряд  и через землю с неба в ад вы мерной поступью пройдите господь архангелы потом мефистофель звуча в гармонии вселенной и в хоре сфер гремя как гром златое солнце неизменно течет предписанным путем непостижимость мирозданья дает нам веру и оплот и словно в первый день созданья величествен вселенной ход и с непонятной быстротою кружась несется шар земной проходят быстрой чередою сиянье дня и мрак ночной бушует море на просторе у твердых скал шумит прибой но в беге сфер земля и море проходят вечно предо мной грозя земле волнуя воды бушуют бури и шумят и грозной цепью сил природы весь мир таинственно объят сверкает пламень истребленья грохочет гром по небесам но вечным светом примиренья творец небес сияет нам и крепнет сила упованья при виде творческой руки творец как в первый день созданья твои творенья велики опять о господи явился ты меж нас за справкой о земле  что делается с нею ты с благосклонностью встречал меня не раз  и вот являюсь я меж челядью твоею прости не мастер я по части громких слов но если б пышный слог я в ход пустить решился сам рассмеялся б ты  ручаться я готов  когда б от смеха ты давно не отучился мне нечего сказать о солнцах и мирах я вижу лишь одни мученья человека смешной божок земли всегда во всех веках чудак такой же он как был в начале века ему немножко лучше бы жилось когда б ему владеть не довелось тем отблеском божественного света что разумом зовет он свойство это он на одно лишь мог употребить  чтоб из скотов скотиной быть позвольте мне  хоть этикет здесь строгий  сравненьем речь украсить он на вид ни дать ни взять  кузнечик долгоногий который по траве то скачет то взлетит и вечно песенку старинную твердит и пусть еще в траве сидел бы он уютно так нет же прямо в грязь он лезет поминутно ты кончил с жалобой одною являешься ты вечно предо мною иль на земле добра совсем уж нет нет что ни говори а плох наш белый свет бедняга человек он жалок так в страданье что мучить бедняка и я не в состоянье но не такой как все он служит поиному ни пить ни есть не хочет поземному как сумасшедший он рассудком слаб что чувствует и сам среди сомнений всегда в свои мечтанья погружен то с неба лучших звезд желает он то на земле  всех высших наслаждений и в нем ничто  ни близкое ни даль  не может утолить грызущую печаль пока еще умом во мраке он блуждает но истины лучом он будет озарен сажая деревцо садовник уже знает какой цветок и плод с него получит он бьюсь об заклад он будет мой прошу я только позволенья  пойдет немедля он за мной пока живет он на груди земной тебе на то не будет запрещенья блуждает человек пока в нем есть стремленья благодарю не надо мертвых мне от трупов я держуся в стороне нет дайте мне здорового вполне таких я мертвецам всегда предпочитаю  как кошка с мышью с ними я играю тебе позволено иди и завладей его душою и если можешь поведи путем превратным за собою  и посрамлен да будет сатана знай чистая душа в своем стремленье смутном сознаньем истины полна сознаньем слабым и минутным игра мне эта не страшна не проиграю я заклада но только знайте если мне поддастся он пусть будет мой вполне триумф победы  вот моя награда пусть вьется он в пыли как тетушка моя достопочтенная змея тогда явись ко мне без колебанья к таким как ты вражды не ведал я хитрец среди всех духов отрицанья ты меньше всех был в тягость для меня слаб человек покорствуя уделу он рад искать покоя  потому дам беспокойного я спутника ему как бес дразня его пусть возбуждает к делу а вы сыны небес и рая  пусть вечно радует вас красота святая и ко всему что есть и будет вновь пусть проникает вас священная любовь и все что временно изменчиво туманно обнимет ваша мысль спокойнопостоянна небо закрывается архангелы расходятся охотно старика я вижу иногда хоть и держу язык приятно убедиться что даже важные такие господа умеют вежливо и с чертом обходиться старинная комната с высокими готическими сводами я философию постиг я стал юристом стал врачом увы с усердьем и трудом и в богословье я проник  и не умней я стал в конце концов чем прежде был глупец я из глупцов магистр и доктор я  и вот тому пошел десятый год я за нос провожу всегда и вижу все ж что не дано нам знанья изныла грудь от жгучего страданья пусть я разумней всех глупцов  писак попов магистров докторов  пусть не страдаю от пустых сомнений пусть не боюсь чертей и привидений пусть в самый ад спуститься я готов  зато я радостей не знаю напрасно истины ищу зато когда людей учу их научить исправить  не мечтаю притом я нищ не ведаю бедняк ни почестей людских ни разных благ так пес не стал бы жить погибли годы вот почему я магии решил предаться жду от духа слов и сил чтоб мне открылись таинства природы чтоб не болтать трудясь по пустякам о том чего не ведаю я сам чтоб я постиг все действия все тайны всю мира внутреннюю связь из уст моих чтоб истина лилась  не слов пустых набор случайный о месяц если б в этот час ты озарил в последний раз меня средь комнаты моей где я познал тоску ночей о если б мог бродить я там в твоем сиянье по горам меж духов реять над вершиной в тумане плавать над долиной науки праздный чад забыть себя росой твоей омыть еще ль в тюрьме останусь я нора проклятая моя здесь солнца луч в цветном окне едваедва заметен мне на полках книги по стенам до сводов комнаты моей  они лежат и здесь и там добыча пыли и червей реторт и банок целый ряд в пыли с приборами стоят на ветхих полках много лет и вот твой мир и вот твой свет еще ль не ясно почему изныла грудь твоя тоской и больно сердцу твоему и жизни ты не рад такой живой природы пышный цвет творцом на радость данный нам ты променял на тлен и хлам на символ смерти  на скелет о прочь беги беги скорей туда на волю нострадам чудесной книгою своей тебя на путь наставит сам к словам природы будь не глух  и ты узнаешь ход светил и дух твой будет полон сил когда ответит духу дух чудесных знаков дивный вид сухой наш ум не объяснит о духи здесь вы в тишине витаете ответьте мне что за блаженство вновь в груди моей зажглось при этом виде сердцу милом как будто счастье жизни юных дней вновь заструилось пламенно по жилам начертан этот знак не бога ли рукой он душу бурную смиряет он сердце бедное весельем озаряет он таинства природы раскрывает пред изумленною душой не бог ли я светло и благодатно все вкруг меня здесь с дивной глубиной все творчество природы предо мной теперь мне слово мудреца понятно в мир духов нам доступен путь но ум твой спит изнемогая о ученик восстань купая в лучах зари земную грудь как в целом части все послушною толпою сливаясь здесь творят живут одна другою как силы вышние в сосудах золотых разносят всюду жизнь божественной рукою и чудным взмахом крыл лазоревых своих витают над землей и в высоте небесной  и стройно все звучит в гармонии чудесной о чудный вид но только вид  увы мне не обнять природы необъятной и где же вы сосцы природы  вы дарующие жизнь струею благодатной которыми живет и небо и земля к которым рвется так больная грудь моя вы всех питаете  что ж тщетно жажду я вот знак другой он чувства мне иные внушает дух земли ты ближе мне родней теперь себя я чувствую сильней  снесу и горе я и радости земные как будто бы вином живительным согрет отважно ринусь я в обширный божий свет мне хочется борьбы готов я с бурей биться  и в час крушенья мне ли устрашиться повсюду мрак и тишина меж туч скрывается луна и лампа тихо угасает над головою в вышине кровавый луч во мгле сверкает и в кровь стесняя сердце мне холодный ужас проникает о дух ты здесь ты близок  о приди как сердце бьется у меня в груди всем существом души всей мощным зовом я порываюсь к чувствам новым явись явись мне  я всем сердцем твой пусть я умру  явись передо мной я вызван мощным голосом твоим к моей ты сфере льнул ее ты порожденье  увы твой вид невыносим не ты ли сам желал с тоской упорной увидеть лик услышать голос мой склонился я на зов отважный твой  и вот я здесь но что за страх позорный сверхчеловек тобою овладел где мощный зов души где тот титан могучий кто мир весь обнимал кто мыслию кипучей сравняться с нами духами хотел ты фауст ли кто звать меня посмел всей силою души неосторожной и что ж моим дыханьем обожжен дрожит в пыли дорожной корчась он как червь презренный и ничтожный во прах перед тобой я не склонюсь челом знай равен я тебе дух пламенный во всем в буре деяний в волнах бытия смерть и рожденье  так на станке проходящих веков тку я живую одежду богов ты целый мир обширный обнимаешь о деятельный дух как близок я тебе ты близок лишь тому кого ты постигаешь  стучатся знаю я помощник это мой погибло все о смерть о муки да он пришел смутить видений чудный рой ничтожный червь сухой науки фауст с неудовольствием отворачивается простите чтото вслух читали вы сейчас из греческой трагедии конечно вот в этом преуспеть желал бы я сердечно ведь декламация в большой цене у нас случалось слышать мне что может в деле этом актер священнику помочь своим советом да коль священник ваш актер и сам как мы нередко видим здесь и там что ж делать мы живем всегда в уединенье едва по праздникам покинешь свой музей и то как в телескоп свет видишь в отдаленье так где ж найти слова чтоб нам учить людей когда в вас чувства нет все это труд бесцельный нет из души должна стремиться речь чтоб прелестью правдивой неподдельной сердца людские тронуть и увлечь а вы сидите да кропайте с чужих пиров объедки подбирайте  и будет пестрый винегрет поддельным пламенем согрет когда таков ваш вкус  пожалуй этим вы угодите дуракам и детям но сердце к сердцу речь не привлечет коль не из сердца ваша речь течет нет в красноречье  истинный успех но в этом признаюсь я поотстал от всех ищи заслуги честной и бесспорной к чему тебе колпак шута позорный когда есть ум и толк в словах у нас речь хороша и без прикрас и если то что говорится дельно  играть словами разве не бесцельно да ваши речи с праздным блеском их в обман лишь вводят вычурой бесплодной не так ли ветер осени холодной шумит меж листьев мертвых и сухих ах боже мой наука так пространна а наша жизнь так коротка мое стремленье к знанью неустанно и всетаки порой грызет меня тоска как много надо сил душевных чтоб добраться до средств лишь чтоб одни источники найти а тут  того гляди  еще на полпути придется бедняку и с жизнию расстаться в пергаменте ль найдем источник мы живой ему ли утолить высокие стремленья о нет в душе своей одной найдем мы ключ успокоенья простите разве мы не радостно следим за духом времени за много лет пред нами как размышлял мудрец и как в сравненье с ним неизмеримо вдаль подвинулись мы сами о да до самых звезд ужасно далеко мой друг прошедшее постичь не так легко его и смысл и дух насколько не забыты  как в книге за семью печатями сокрыты то что для нас на первый беглый взгляд дух времени  увы  не что иное как отраженье века временное в лице писателя его лишь дух и склад от этого в отчаянье порою приходишь хоть беги куда глаза глядят все пыльный хлам да мусор пред тобою и рад еще когда придется прочитать о важном действе с пышным представленьем и наставительным в конце нравоученьем как раз для кукольной комедии под стать а мир а дух людей их сердце без сомненья всяк хочет чтонибудь узнать на этот счет да но что значит  знать вот в чем все затрудненья кто верным именем младенца наречет где те немногие кто век свой познавали ни чувств своих ни мыслей не скрывали с безумной смелостью толпе навстречу шли их распинали били жгли однако поздно нам пора расстаться оставим этот разговор а я  хоть навсегда готов бы здесь остаться чтоб только продолжать такой ученый спор ну что ж хоть завтра  в пасху в воскресенье  позвольте вам еще вопросдругой задать ужасное во мне кипит к наукам рвенье хоть много знаю я но все хотел бы знать он все надеется без скуки безотрадной копается в вещах скучнейших и пустых сокровищ ищет он рукою жадной  и рад когда червей находит дождевых 

Запишем обработанные данные в текстовый файл:

In [20]:
train_path = "faust_train.txt"
with open(train_path, "w") as f:
    f.write(text)

torch.Size([1, 45])

## Предобученная sberbank-ai GPT2

Возьмите предобученную модель и попробуйте сгенерировать текст с ее помощью. Оцените результаты.

Весь текст подать на вход не получится. Подайте первые 30 слов.

In [29]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel


model_name_or_path = "sberbank-ai/rugpt3small_based_on_gpt2"
tokenizer = GPT2Tokenizer.from_pretrained(model_name_or_path)
model = GPT2LMHeadModel.from_pretrained(model_name_or_path)

first_30_words = " ".join(text.split()[:30])
input_ids = tokenizer.encode(first_30_words, return_tensors="pt")

sample_output = model.generate(
    input_ids,
    do_sample=False,
    max_length=100,
    num_beams=1,
    pad_token_id=tokenizer.eos_token_id,
)
generated_text = tokenizer.decode(sample_output[0], skip_special_tokens=True)
clear_output()

In [30]:
print(generated_text)

вы вновь со мной туманные виденья мне в юности мелькнувшие давно вас удержу ль во власти вдохновенья былым ли снам явиться вновь дано из сумрака из тьмы полузабвенья восстали вы в вышних, и в вышних, и в вышних, и в вышних, и в вышних, и в вышних, и в вышних, и в вышних, и в вышних, и в вышних, и в вышних, и

## Файнтюнинг sberbank-ai GPT2

Дообучите модель. Для этого сначала создадим датасет и `data_collator`, который нарезает текст на оптимальные по длине куски:

In [32]:
from transformers import  DataCollatorForLanguageModeling

class TextDataset(Dataset):
    def __init__(self, tokenizer, file_path, block_size=64):
        with open(file_path, encoding="utf-8") as f:
            text = f.read()
        tokenized = tokenizer(text, return_tensors="pt")["input_ids"][0]
        self.examples = [
            tokenized[i : i + block_size]
            for i in range(0, len(tokenized) - block_size + 1, block_size)
        ]

    def __len__(self):
        return len(self.examples)

    def __getitem__(self, i):
        return {"input_ids": self.examples[i], "labels": self.examples[i].clone()}


train_path = "Faust.txt"


train_dataset = TextDataset(tokenizer=tokenizer, file_path=train_path, block_size=64)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)
clear_output()

In [37]:
train_dataset.__len__()

1771

In [48]:
from transformers import Trainer, TrainingArguments
from transformers import get_linear_schedule_with_warmup
model.to(device)

# Your code here
training_args = TrainingArguments(
    output_dir='./res_task_1_fine_tune_sberbank-ai GPT2',
    #overwrite_output_dir=True, #overwrite the content of the output directory
    num_train_epochs=1, # number of training epochs
    per_device_train_batch_size=8, # batch size for training
    per_device_eval_batch_size=8,  # batch size for evaluation
    warmup_steps=10,# number of warmup steps for learning rate scheduler
    gradient_accumulation_steps=4, # to make "virtual" batch size larger
    report_to="none",
)

optimizer = torch.optim.AdamW(model.parameters(), lr=5e-3)
total_steps = train_dataset.__len__() // 32
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=training_args.warmup_steps,
    num_training_steps=total_steps,
)


trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset,
    optimizers = [optimizer, scheduler] # Your code here # Optimizer and lr scheduler
)

In [49]:
trainer.train()

`loss_type=None` was set in the config but it is unrecognized. Using the default loss: `ForCausalLMLoss`.

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=56, training_loss=4.294544492449079, metrics={'train_runtime': 41.1047, 'train_samples_per_second': 43.085, 'train_steps_per_second': 1.362, 'total_flos': 84095865520128.0, 'train_loss': 4.294544492449079, 'epoch': 1.0})

In [50]:
# Probability beam sampling example
text = "Ходил"
input_ids = tokenizer.encode(text, return_tensors="pt").to(device)
model.eval()
with torch.no_grad():
    out = model.generate(
        input_ids,
        do_sample=True,
        num_beams=2,
        temperature=1.5,
        top_p=0.9,
        max_length=200,
    )

generated_text = list(map(tokenizer.decode, out))[0]

In [51]:
print(generated_text)

Ходил бы ты, милый!
да, я не прочь, чтоб ты был!
тебе бы в ту ночь было,
как я вижу, лучше, чем мне.
а теперь, увы!
мне так жаль!
с тех пор, как был в нем,
он стал мне сниться,
как наяву.
я знаю, где он,
где ты;
он там; я его знаю,
а он нет.
я знаю, кто он,
кто он.
он мне знаком; я слышал его,
но, к счастью, он мне не знаком,
я не слышал его и не знаю.
ну, я пойду, милый,
посмотрим, где он прячется!
и, клянусь, ты знаешь, где он!
как ты его знаешь?
что ж, он здесь! я его знаю.
я знаю, где он; я его знаю,
а он нигде не живет;
я слышал

## Другая модель с HuggingFace

In [52]:
from transformers import GPT2Tokenizer, GPT2LMHeadModel


tokenizer = GPT2Tokenizer.from_pretrained(
    "ai-forever/rugpt3small_based_on_gpt2", clean_up_tokenization_spaces=False
)
model = GPT2LMHeadModel.from_pretrained("ai-forever/rugpt3small_based_on_gpt2")

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

special_tokens_map.json:   0%|          | 0.00/574 [00:00<?, ?B/s]

config.json:   0%|          | 0.00/720 [00:00<?, ?B/s]

pytorch_model.bin:   0%|          | 0.00/551M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/149 [00:00<?, ?it/s]

The tied weights mapping and config for this model specifies to tie transformer.wte.weight to lm_head.weight, but both are present in the checkpoints, so we will NOT tie them. You should update the config with `tie_word_embeddings=False` to silence this warning
GPT2LMHeadModel LOAD REPORT from: ai-forever/rugpt3small_based_on_gpt2
Key                                     | Status     |  |
----------------------------------------+------------+--+-
transformer.h.{0...11}.attn.masked_bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

In [54]:
from transformers import DataCollatorForLanguageModeling

train_path = "Faust.txt"

train_dataset = TextDataset(tokenizer=tokenizer, file_path=train_path, block_size=64)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)
clear_output()

In [55]:
from transformers import Trainer, TrainingArguments
from transformers import get_linear_schedule_with_warmup
model.to(device)

# Your code here
training_args = TrainingArguments(
    output_dir='./res_task_1_fine_tune_rugpt3small_based_on_gpt2',
    #overwrite_output_dir=True, #overwrite the content of the output directory
    num_train_epochs=1, # number of training epochs
    per_device_train_batch_size=8, # batch size for training
    per_device_eval_batch_size=8,  # batch size for evaluation
    warmup_steps=10,# number of warmup steps for learning rate scheduler
    gradient_accumulation_steps=4, # to make "virtual" batch size larger
    report_to="none",
)

optimizer = torch.optim.AdamW(model.parameters(), lr=5e-5)
total_steps = train_dataset.__len__() // 32
scheduler = get_linear_schedule_with_warmup(
    optimizer,
    num_warmup_steps=training_args.warmup_steps,
    num_training_steps=total_steps,
)


trainer = Trainer(
    model=model,
    args=training_args,
    data_collator=data_collator,
    train_dataset=train_dataset,
    optimizers = [optimizer, scheduler] # Your code here # Optimizer and lr scheduler
)

In [56]:
trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

TrainOutput(global_step=56, training_loss=4.294544492449079, metrics={'train_runtime': 47.0256, 'train_samples_per_second': 37.66, 'train_steps_per_second': 1.191, 'total_flos': 84095865520128.0, 'train_loss': 4.294544492449079, 'epoch': 1.0})

In [57]:
# Probability beam sampling example
text = "все"
input_ids = tokenizer.encode(text, return_tensors="pt").to(device)
model.eval()
with torch.no_grad():
    out = model.generate(
        input_ids,
        do_sample=True,
        num_beams=1,
        temperature=1.6,
        top_p=0.7,
        max_length=100,
        pad_token_id=tokenizer.eos_token_id,
    )

generated_text = list(map(tokenizer.decode, out))[0]

In [58]:
print(generated_text)

все
так же сильно ты был прекрасен, и
все, что для тебя сейчас, не так уж плохо!
мне было с тобою хорошо:
и тебе, и ему я рад,
что мы еще так прекрасны.
но, когда ты был так слаб,
как это случилось, мы еще так сильны.
ты должен был нам все дать,
так ты нам все испортил;
у нас нет и сил, нет и любви.
нет, ничего не выйдет

In [59]:
del model
del tokenizer

torch.cuda.empty_cache()

## Формат результата

Сгенерированный текст

Пример текста:

"все все от бесстыдные старой

все в нем получше все стремленья

поддержки с собой в сердце воздух своей

и в вечной страсти восстанет свой предлог

привет вам слуга в сладком страшней стране

и в мире все вражда станет станет

в поле на пользу своим воспоминанья"

# Задание 2. Классификация с помощью BERT

Возьмите набор данных эмоциональных окрасок отзывов [emotions dataset 🛠️[doc]](https://huggingface.co/datasets/emotion). В датасете 5 классов. Получите эмбеддинг из BERT-подобного кодировщика. Классифицируйте тексты с помощью методов ML или  нейросети, используя эмбеддинги в качестве входов.

Произведите fine-tuning кодировщика на ваших данных (классификатор на основе BERT) и сравните, как изменилось качество классификации.

Импорт необходимых библиотек:

In [3]:
import torch
import evaluate
import numpy as np
import pandas as pd
from datasets import Dataset
from datasets import load_dataset
from datasets.dataset_dict import DatasetDict
from transformers import Trainer, TrainingArguments
from transformers import AutoTokenizer, AutoModel
from transformers import AutoModelForSequenceClassification
from sklearn.metrics import classification_report
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import cross_val_score
from sklearn.model_selection import train_test_split
from IPython.display import clear_output

Взглянем на датасет.

In [2]:
train = load_dataset("SetFit/emotion", split="train")
clear_output()

train_df = pd.DataFrame({"text": train["text"], "labels": train["label"]})
train_df.head()

                                                text  labels
0                            i didnt feel humiliated       0
1  i can go from feeling so hopeless to so damned...       0
2   im grabbing a minute to post i feel greedy wrong       3
3  i am ever feeling nostalgic about the fireplac...       2
4                               i am feeling grouchy       3

Инициализация токенайзера и модели. Перед тем, как отправить текст в модель, его следует токенизировать.

**Учитывайте**, что:
* Мы посмотрели несколько способов получения эмбеддингов из моделей BERT. Воспользуйтесь одним из них.
* Длина эмбеддинга больше 200 в данной задаче не потребуется. Чем длиннее эмбеддинг, тем медленнее всё будет учиться.
* В каждой части задания нужно задать по отдельной модели.
* Библиотеки в первой и второй части задания могут конфликтовать. Используйте "перезапуск сеанса", если так случилось.

Возьмите модель `bert-tiny` и соответствующий токенизатор.

In [7]:
from transformers import AutoTokenizer, AutoModel

tokenizer = AutoTokenizer.from_pretrained("google/bert_uncased_L-2_H-128_A-2")
model = AutoModel.from_pretrained("google/bert_uncased_L-2_H-128_A-2")
clear_output()
model.to(device)

BertModel(
  (embeddings): BertEmbeddings(
    (word_embeddings): Embedding(30522, 128, padding_idx=0)
    (position_embeddings): Embedding(512, 128)
    (token_type_embeddings): Embedding(2, 128)
    (LayerNorm): LayerNorm((128,), eps=1e-12, elementwise_affine=True)
    (dropout): Dropout(p=0.1, inplace=False)
  )
  (encoder): BertEncoder(
    (layer): ModuleList(
      (0-1): 2 x BertLayer(
        (attention): BertAttention(
          (self): BertSelfAttention(
            (query): Linear(in_features=128, out_features=128, bias=True)
            (key): Linear(in_features=128, out_features=128, bias=True)
            (value): Linear(in_features=128, out_features=128, bias=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
          (output): BertSelfOutput(
            (dense): Linear(in_features=128, out_features=128, bias=True)
            (LayerNorm): LayerNorm((128,), eps=1e-12, elementwise_affine=True)
            (dropout): Dropout(p=0.1, inplace=False)
          )
        )
        (intermediate): BertIntermediate(
          (dense): Linear(in_features=128, out_features=512, bias=True)
          (intermediate_act_fn): GELUActivation()
        )
        (output): BertOutput(
          (dense): Linear(in_features=512, out_features=128, bias=True)
          (LayerNorm): LayerNorm((128,), eps=1e-12, elementwise_affine=True)
          (dropout): Dropout(p=0.1, inplace=False)
        )
      )
    )
  )
  (pooler): BertPooler(
    (dense): Linear(in_features=128, out_features=128, bias=True)
    (activation): Tanh()
  )
)

Посмотрим, как устроен датасет и какой у него баланс классов:

In [10]:
# Your code here
print("Размер датасета:", len(train_df))
print("Баланс:")
print(train_df["labels"].value_counts().sort_index())

Размер датасета: 16000
Баланс:
labels
0    4666
1    5362
2    1304
3    2159
4    1937
5     572
Name: count, dtype: int64

Оставим 5000 объектов, поделив их на обучение, валидацию, тест.

Будем семплировать, в функцию `sample` из `pandas` подадим веса для каждого объекта. Создадим столбец, в каждой строке которого будет частота семплирования.

In [11]:
train_df["freq"] = len(train_df) / train_df.groupby("labels")["labels"].transform("count")
sampledf = train_df.sample(weights=train_df.freq)

In [12]:
sampledf = train_df.sample(5000, weights=train_df.freq)
sampledf["labels"].value_counts()

labels
0    1010
1     991
3     884
4     837
2     780
5     498
Name: count, dtype: int64

Также имеет смысл проверить, что в колонке `labels` данные типа `int`. Если нет, то привести к этому типу.

In [13]:
sampledf["labels"] = sampledf["labels"].astype(int)

sample = list(sampledf["text"])
labels = list(sampledf["labels"])

Разделите данные на `train`, `val`, `test`. Получите `x_train`, `y_train` и т.д.

In [14]:
from sklearn.model_selection import train_test_split

# Your code here
x_train, x_temp, y_train, y_temp = train_test_split(
    sample, labels, test_size=0.2, random_state=42, stratify=labels
)
x_val, x_test, y_val, y_test = train_test_split(
    x_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp
)

print(f"Train: {len(x_train)}, Val: {len(x_val)}, Test: {len(x_test)}")

Train: 4000, Val: 500, Test: 500

Проверьте, какие объекты и в каком количестве представлены в метках в трёх выборках.

In [16]:
# Your code here
print("Train")
print(pd.Series(y_train).value_counts().sort_index())
print("Val")
print(pd.Series(y_val).value_counts().sort_index())
print("Tes")
print(pd.Series(y_test).value_counts().sort_index())

Train
0    808
1    793
2    624
3    707
4    670
5    398
Name: count, dtype: int64
Val
0    101
1     99
2     78
3     88
4     84
5     50
Name: count, dtype: int64
Tes
0    101
1     99
2     78
3     89
4     83
5     50
Name: count, dtype: int64

Получите и сохраните векторные представления текстов, которые возвращает модель. Например, вот таким образом. В `x_train` сейчас текст в виде букв.

In [18]:
train_emb = []
for t in x_train:
    encoded = tokenizer.encode(t, return_tensors="pt").to(device)
    output = model(encoded)["pooler_output"][0].detach().cpu()
    train_emb.append(output)

train_emb = torch.stack(train_emb).numpy()

In [19]:
val_emb = []
for t in x_val:
    encoded = tokenizer.encode(t, return_tensors="pt").to(device)
    output = model(encoded)["pooler_output"][0].detach().cpu()
    val_emb.append(output)

val_emb = torch.stack(val_emb).numpy()

In [20]:
test_emb = []
for t in x_test:
    encoded = tokenizer.encode(t, return_tensors="pt").to(device)
    output = model(encoded)["pooler_output"][0].detach().cpu()
    test_emb.append(output)

test_emb = torch.stack(test_emb).numpy()

Возьмите ML-классификатор, обучите его и постройте `classification_report`.

Базово можно взять `RandomForestClassifier`.

In [21]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier(n_estimators=100, random_state=42, n_jobs=-1)
clf.fit(train_emb, y_train)

RandomForestClassifier(n_jobs=-1, random_state=42)

In [22]:
from sklearn.metrics import classification_report

y_pred = clf.predict(test_emb)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.36      0.49      0.41       101
           1       0.39      0.46      0.42        99
           2       0.45      0.37      0.41        78
           3       0.26      0.28      0.27        89
           4       0.31      0.28      0.29        83
           5       0.70      0.14      0.23        50

    accuracy                           0.36       500
   macro avg       0.41      0.34      0.34       500
weighted avg       0.39      0.36      0.35       500

Здесь не требуется получить 100% Presicion и Recall. Однако проверьте, что вы верно разделили данные на 3 подвыборки и что значения метрик не находятся в районе нуля.

**Попробуйте дообучить BERT и произвести классификацию заново.**

Загрузим данные заново. В этом разделе необходимо создать `Dataset` в формате `HuggingFace`.

In [6]:
train = load_dataset("SetFit/emotion", split="train")
clear_output()

train_df = pd.DataFrame({"text": train["text"], "labels": train["label"]})
train_df.head()

                                                text  labels
0                            i didnt feel humiliated       0
1  i can go from feeling so hopeless to so damned...       0
2   im grabbing a minute to post i feel greedy wrong       3
3  i am ever feeling nostalgic about the fireplac...       2
4                               i am feeling grouchy       3

Заново разделите данные на данные на `train`, `val`, `test`, как делали выше. Мы вновь начинаем с текстов в привычном буквенном формате.

In [7]:
# Your code here
train_df["freq"] = len(train_df) / train_df.groupby("labels")["labels"].transform("count")
sampledf = train_df.sample(5000, weights=train_df.freq, random_state=42)
sampledf["labels"] = sampledf["labels"].astype(int)

sample = list(sampledf["text"])
labels = list(sampledf["labels"])

x_train, x_temp, y_train, y_temp = train_test_split(
    sample, labels, test_size=0.2, random_state=42, stratify=labels
)
x_val, x_test, y_val, y_test = train_test_split(
    x_temp, y_temp, test_size=0.5, random_state=42, stratify=y_temp
)

In [8]:
import evaluate

metric = evaluate.load("f1")


def compute_metrics(eval_pred):
    logits, labels = eval_pred
    predictions = np.argmax(logits, axis=-1)
    return metric.compute(
        predictions=predictions, references=labels, average="weighted"
    )

In [9]:
from datasets import Dataset
from datasets.dataset_dict import DatasetDict

d = {
    "train": Dataset.from_dict({"label": y_train, "text": x_train}),
    "val": Dataset.from_dict({"label": y_val, "text": x_val}),
    "test": Dataset.from_dict({"label": y_test, "text": x_test}),
}

dataset = DatasetDict(d)

In [10]:
dataset

DatasetDict({
    train: Dataset({
        features: ['label', 'text'],
        num_rows: 4000
    })
    val: Dataset({
        features: ['label', 'text'],
        num_rows: 500
    })
    test: Dataset({
        features: ['label', 'text'],
        num_rows: 500
    })
})

Настройте токенизатор (если это не было сделано выше) так, чтобы производились дополнение (padding) и обрезка предложений. Имеет смысл указать длину получаемых векторных представлений (`model_max_length`).

In [11]:
# Your code here
tokenizer_bert = AutoTokenizer.from_pretrained(
    "google/bert_uncased_L-2_H-128_A-2",
    model_max_length=128,
)

Напишите функцию, которая будет токенизировать ваш текст в `DatasetDict`.

In [12]:
# Your code here
def tokenize_function(examples):
    return tokenizer_bert(
        examples["text"],
        padding="max_length",
        truncation=True,
    )

Токенизируйте ваши данные:

In [13]:
# Your code here
tokenized_data = dataset.map(tokenize_function, batched=True)
tokenized_data = tokenized_data.rename_column("label", "labels")

Map:   0%|          | 0/4000 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

Map:   0%|          | 0/500 [00:00<?, ? examples/s]

Посмотрите, как  выглядит ваш `DatasetDict`, какие размеры (`shape`) сущностей, которые он содержит. Выведите первый объект из `train`.

Там должен находиться как исходный текст, так и его представление в виде токенов (из токенизатора, не из модели).

In [14]:
# Your code here
print("struct:")
print(tokenized_data)

struct:
DatasetDict({
    train: Dataset({
        features: ['labels', 'text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 4000
    })
    val: Dataset({
        features: ['labels', 'text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 500
    })
    test: Dataset({
        features: ['labels', 'text', 'input_ids', 'token_type_ids', 'attention_mask'],
        num_rows: 500
    })
})

Импортируйте модель с учётом того, что вы уже решаете не просто задачу построения эмбеддингов, а задачу классификации. Укажите верное число классов в ней.

In [23]:
from transformers import AutoModelForSequenceClassification

model_for_classification = AutoModelForSequenceClassification.from_pretrained(
    "google/bert_uncased_L-2_H-128_A-2",
    num_labels=6,
)
model_for_classification.to(device)

for param in model_for_classification.parameters():
    param.data = param.data.contiguous()

Loading weights:   0%|          | 0/39 [00:00<?, ?it/s]

BertForSequenceClassification LOAD REPORT from: google/bert_uncased_L-2_H-128_A-2
Key                                        | Status     |
-------------------------------------------+------------+-
cls.seq_relationship.bias                  | UNEXPECTED |
cls.predictions.transform.LayerNorm.weight | UNEXPECTED |
cls.predictions.transform.dense.bias       | UNEXPECTED |
cls.predictions.transform.LayerNorm.bias   | UNEXPECTED |
cls.predictions.transform.dense.weight     | UNEXPECTED |
cls.predictions.bias                       | UNEXPECTED |
cls.seq_relationship.weight                | UNEXPECTED |
classifier.bias                            | MISSING    |
classifier.weight                          | MISSING    |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.
- MISSING	:those params were newly initialized because missing from the checkpoint. Consider training on your downstream task.

In [24]:
# model

Задайте параметры, обучите модель:

In [28]:
from transformers import Trainer, TrainingArguments

# Your code here
training_args = TrainingArguments(
    output_dir="./my_awesome_model",
    learning_rate=2e-3,
    per_device_train_batch_size=32,
    per_device_eval_batch_size=32,
    num_train_epochs=3, #,#about 1.5 minutes for 1 epoch
    weight_decay=0.01,#,
    eval_strategy="epoch",#,
    save_strategy="epoch",#,
    load_best_model_at_end=True,#,
    push_to_hub=False,
    report_to="none",
)



trainer = Trainer(
    model=model_for_classification,                         # the instantiated 🤗 Transformers model to be trained
    args=training_args,                  # training arguments, defined above
    train_dataset=tokenized_data['train'],         # training dataset
    eval_dataset=tokenized_data['val'],
    processing_class=tokenizer_bert,
    compute_metrics=compute_metrics
)

trainer.train()

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.weight', 'bert.embeddings.LayerNorm.bias', 'bert.encoder.layer.0.attention.output.LayerNorm.weight', 'bert.encoder.layer.0.attention.output.LayerNorm.bias', 'bert.encoder.layer.0.output.LayerNorm.weight', 'bert.encoder.layer.0.output.LayerNorm.bias', 'bert.encoder.layer.1.attention.output.LayerNorm.weight', 'bert.encoder.layer.1.attention.output.LayerNorm.bias', 'bert.encoder.layer.1.output.LayerNorm.weight', 'bert.encoder.layer.1.output.LayerNorm.bias'].
There were unexpected keys in the checkpoint model loaded: ['bert.embeddings.LayerNorm.beta', 'bert.embeddings.LayerNorm.gamma', 'bert.encoder.layer.0.attention.output.LayerNorm.beta', 'bert.encoder.layer.0.attention.output.LayerNorm.gamma', 'bert.encoder.layer.0.output.LayerNorm.beta', 'bert.encoder.layer.0.output.LayerNorm.gamma', 'bert.encoder.layer.1.attention.output.LayerNorm.beta', 'bert.encoder.layer.1.attention.output.LayerNorm.gamma', 'bert.encoder.layer.1.output.LayerNorm.beta', 'bert.encoder.layer.1.output.LayerNorm.gamma'].

TrainOutput(global_step=375, training_loss=0.6778890787760417, metrics={'train_runtime': 13.4207, 'train_samples_per_second': 894.142, 'train_steps_per_second': 27.942, 'total_flos': 3816216576000.0, 'train_loss': 0.6778890787760417, 'epoch': 3.0})

Мы дообучили модель! Теперь проверим качество предсказания на тесте.

Можете использовать `trainer.predict`.

In [29]:
# Your code here
predictions = trainer.predict(tokenized_data["test"])
y_pred = np.argmax(predictions.predictions, axis=-1)
y_true = predictions.label_ids

In [30]:
from sklearn.metrics import classification_report

print(classification_report(y_true, y_pred, zero_division=0))

              precision    recall  f1-score   support

           0       0.86      0.91      0.89        98
           1       0.94      0.83      0.88        99
           2       0.85      0.97      0.91        77
           3       0.91      0.90      0.90        88
           4       0.87      0.76      0.81        88
           5       0.84      0.98      0.91        50

    accuracy                           0.88       500
   macro avg       0.88      0.89      0.88       500
weighted avg       0.88      0.88      0.88       500

Если у вас получилось 100%, проверьте, что с чем вы сравниваете. По умолчанию `predict` возвращает логиты и истинные метки, которые были изначально в переданном объекте.

## Формат результата

Получить значение качества классификации.